numbers=[1,2,3,4,5,6,7,8,9,10]
console.log(numbers);
console.log(numbers[0]);
console.log(numbers[1]);
numbers.pop();
console.log(numbers);
numbers.shift();
console.log(numbers);
numbers.splice(2,4);
console.log(numbers);